Fixing for error: ``` Traceback (most recent call last):   File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context     self.dialect.do_execute(   File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute     cursor.execute(statement, parameters) psycopg2.errors.StringDataRightTruncation: value too long for type character(64)
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/sean/github/rh-augur-new-dev/augur/tasks/github/releases/tasks.py", line 13, in collect_releases
    releases_model(session, repo.repo_git, repo.repo_id)
  File "/home/sean/github/rh-augur-new-dev/augur/tasks/github/releases/core.py", line 205, in releases_model
    insert_release(session, repo_id, data['owner'], release, True)
  File "/home/sean/github/rh-augur-new-dev/augur/tasks/github/releases/core.py", line 79, in insert_release
    session.insert_data(release_inf,Release,['release_id'])
  File "/home/sean/github/rh-augur-new-dev/augur/application/db/session.py", line 147, in insert_data
    connection.execute(stmnt)
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/sean/github/virtualenv/k12/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character(64)

[SQL: INSERT INTO augur_data.releases (release_id, repo_id, release_name, release_author, release_created_at, release_tag_name, tag_only) VALUES (%(release_id_m0)s, %(repo_id_m0)s, %(release_name_m0)s, %(release_author_m0)s, %(release_created_at_m0)s, %(release_tag_name_m0)s, %(tag_only_m0)s) ON CONFLICT (release_id) DO UPDATE SET release_id = excluded.release_id, repo_id = excluded.repo_id, release_name = excluded.release_name, release_author = excluded.release_author, release_created_at = excluded.release_created_at, release_tag_name = excluded.release_tag_name, tag_only = excluded.tag_only]
[parameters: {'release_id_m0': 'MDM6UmVmMTMxOTAxODM1OnJlZnMvdGFncy92MjAxMzA2MDRhXzVfMF8wX3N0YWJsZQ==', 'repo_id_m0': 25676, 'release_name_m0': 'v20130604a_5_0_0_stable', 'release_author_m0': 'Thorsten Schenkel_thorsten.schenkel@compeople.de', 'release_created_at_m0': '2013-06-04T12:52:24+02:00', 'release_tag_name_m0': 'v20130604a_5_0_0_stable', 'tag_only_m0': True}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
```