Issue with extremely large repository pull_requests fixed by adding incremental inserts.
Error Details:
- OS Level OOM Error Log
- Augur error log
- Database state showing that the killed collection process leaves all subsequent core tasks hanging after the OOM.

```bash
May 11 08:40:26 ip-172-31-43-26 kernel: [196984.540841] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
May 11 08:40:26 ip-172-31-43-26 kernel: [196984.543107] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-330.scope,task=celery,pid=2787413,uid=1000
May 11 08:40:26 ip-172-31-43-26 kernel: [196984.543138] Out of memory: Killed process 2787413 (celery) total-vm:14657984kB, anon-rss:8728064kB, file-rss:5632kB, shmem-rss:0kB, UID:1000 pgtables:17844kB oom_score_adj:0
May 11 11:33:17 ip-172-31-43-26 kernel: [207355.229829] Softwar~cThread invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=0
May 11 11:33:17 ip-172-31-43-26 kernel: [207355.229874]  oom_kill_process+0x10c/0x1b0
May 11 11:33:17 ip-172-31-43-26 kernel: [207355.229884]  __alloc_pages_may_oom+0x114/0x1e0
May 11 11:33:17 ip-172-31-43-26 kernel: [207355.230235] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
May 11 11:33:17 ip-172-31-43-26 kernel: [207355.232557] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-330.scope,task=celery,pid=2787363,uid=1000
May 11 11:33:17 ip-172-31-43-26 kernel: [207355.232580] Out of memory: Killed process 2787363 (celery) total-vm:14415148kB, anon-rss:8500952kB, file-rss:9216kB, shmem-rss:0kB, UID:1000 pgtables:17364kB oom_score_adj:0

augur.tasks.github.pull_requests.tasks.collect_pull_requests cf2337d6-6adb-4b0b-a47d-cfd74c01d86a
Name 	augur.tasks.github.pull_requests.tasks.collect_pull_requests
UUID 	cf2337d6-6adb-4b0b-a47d-cfd74c01d86a
State 	FAILURE
args 	('https://github.com/kubernetes/kubernetes',)
kwargs 	{}
Result 	None
Received 	2024-05-11 02:19:36.542103 UTC
Started 	2024-05-11 02:19:36.543418 UTC
Failed 	2024-05-11 05:03:50.075814 UTC
Retries 	0
Worker 	core:c1d207996f614c648319b1c800672fce@ip-172-31-43-26
Exception 	WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 35.')
Timestamp 	2024-05-11 05:03:50.075814 UTC
Traceback

Traceback (most recent call last):
  File "/home/ubuntu/github/virtualenvs/hosted/lib/python3.11/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 35.

Clock 	56697
Root 	<Task: augur.tasks.start_tasks.augur_collection_monitor(f93b7451-cfb2-42fc-a7b8-4ea8fe59d647) SUCCESS clock:222>
Root id 	f93b7451-cfb2-42fc-a7b8-4ea8fe59d647
Parent 	<Task: augur.tasks.github.detect_move.tasks.detect_github_repo_move_core(41327ca8-c735-44c5-a536-38acd8968e42) SUCCESS clock:244>
Parent id 	41327ca8-c735-44c5-a536-38acd8968e42
Children

Augur thinks we are still collecting, so it will never get to messages:
repo_id	core_data_last_collected	core_status	core_task_id	secondary_data_last_collected	secondary_status	secondary_task_id	event_last_collected	facade_status	facade_data_last_collected	facade_task_id	core_weight	facade_weight	secondary_weight	issue_pr_sum	commit_sum	ml_status	ml_data_last_collected	ml_task_id	ml_weight
123948	2024-02-09 04:43:29	Collecting	9bef29e6-9519-4acb-8469-24c6857c8d92	2022-12-20 00:00:00	Success			Success	2024-04-10 06:07:05		-1249186522	121948	-52204734437	203819	121948	Pending			-12149126357```