Working on fixing rare error.
```
2022-04-14 17:10:28,581,581ms [PID: 984587] workers.pull_request_worker.50471 [DEBUG] Extracting data from source in pr model. ERROR: invalid literal for int() with base 10: '909941810.0'
Traceback (most recent call last):
  File "/bigdisk/augur-vmware/workers/pull_request_worker/pull_request_worker.py", line 554, in pk_source_increment_insert
    prs_insert = [
  File "/bigdisk/augur-vmware/workers/pull_request_worker/pull_request_worker.py", line 558, in <listcomp>
    'pr_src_id': int(str(pr['id']).encode(encoding='UTF-8').decode(encoding='UTF-8')),#1-22-2022 inconsistent casting; sometimes int, sometimes float in bulk_insert
ValueError: invalid literal for int() with base 10: '909941810.0'
2022-04-14 17:10:28,581,581ms [PID: 984587] workers.pull_request_worker.50471 [INFO] 0 insertions are needed and 0 updates are needed for pull_requests
2022-04-14 17:10:28,581,581ms [PID: 984587] workers.pull_request_worker.50471 [INFO] Preparing to enrich data.

2022-04-14 19:07:07,129,129ms [PID: 984587] workers.pull_request_worker.50471 [DEBUG] Extracting data from source in pr model. ERROR: 'cntrb_id'
Traceback (most recent call last):
  File "/bigdisk/augur-vmware/workers/pull_request_worker/pull_request_worker.py", line 554, in pk_source_increment_insert
    prs_insert = [
  File "/bigdisk/augur-vmware/workers/pull_request_worker/pull_request_worker.py", line 572, in <listcomp>
    int(pr['cntrb_id']) ## cast as an int because of an otherwise inexplicable error.
KeyError: 'cntrb_id'
2022-04-14 19:07:07,130,130ms [PID: 984587] workers.pull_request_worker.50471 [INFO] 0 insertions are needed and 0 updates are needed for pull_requests
2022-04-14 19:07:07,130,130ms [PID: 984587] workers.pull_request_worker.50471 [INFO] Preparing to enrich data.
```